### ISSUE TITLE
FFViperCompat

### ISSUE THREAD

**Issue by PeterMeyer** [FreeFalcon/freefalcon-central#1]
Right now weather Module will not initialize correctly after FFViper was compiled
correctly. This has to do with General overrides. The Problem is known and is
not solved read.

Topics: FRead Problem, past bug in VC++ Compiler.

**Comment by vinnydiehl** [comment]
I assigned @Multifalcon to this bug as you told me he was hunting it. The bug appears to be in [this method](https://github.com/FreeFalcon/freefalcon-central/blob/fbdcb9a5ed96fb056be29a1d6512fb1a0ca303f2/src/graphics/weather/tod.cpp#L637). There are a bunch of `fscanf()` calls and the function seems to have been overridden somewhere else in the code.

The problem here is that `fscanf()` simply does not work anymore. This particular freeze is caused by an infinite loops sprung by the first call of the function in the method linked above (pop some breakpoints around it to see for yourself). The `fscanf()` call does not affect `buffer` in any way, and therefore it never satisfies any of the chain of conditionals that follow and never breaks, looping that forever.

**Comment by PeterMeyer** [comment]
Yeah lets look to the compatlib for a quick fix and hopefully we find the override.
It would be the dream if some old coder of Falcon can bring light into the dark.

**Comment by vinnydiehl** [comment]
Unfortunately the person that introduced the override to the code probably hasn't touched Falcon in 8 years.

**Comment by Multifalcon** [comment]
Morning, finally I have connection.

You are right about the bug, in the incialization, unfortunately, I must delay the bug fix, for reallfe issues, ASAP I will come to the FFcode.

**Comment by PlutoniumHeart** [comment]
Hi all, I believe I have found and fixed this bug, I am wondering how I should upload this fix. 

Thanks!

Plutonium

**Comment by vinnydiehl** [comment]
@Multifalcon: That's not a problem, personal issues are well understood.

@PlutoniumHeart: If you think you have it fixed, take the following steps to get the patch to us for review:
1. Fork this repository
2. Clone your fork to your computer
3. Create a feature branch for the fix (`git checkout -b feature/file-read-fix`)
4. Apply your changes to the code
5. Commit the changes (you can reference this issue in the commit message by mentioning #1 somewhere in it)
6. Push the commit(s) to your fork (`git push origin feature/file-read-fix`)
7. Send a pull request

If you're having too much trouble with this, send me an email or a PM on the forums and you can give me the fix to apply in some other manner. Doing this through GitHub will give you proper credit, though.

**Comment by PlutoniumHeart** [comment]
@gbchaosmaster: Hi, I should be able to do that tomorrow. But in the case that I had a problem doing this, I will let you know. 

Thanks.

Plutonium

**Comment by vinnydiehl** [comment]
@PlutoniumHeart: Alrighty, I look forward to seeing your changes. The sooner we can get rid of this issue, the better.

Cheers,
Vinny

**Comment by PeterMeyer** [comment]
Good morning.
Awsome news! Good Job Plutonium ;D 
@Plutonium I get a Bounce message from the Mailinglist. Can you just send a fresh/new post to the List with a new subject abut this bug to it and describe what you have done? You can also send yor Patch to the Mailing list.

All the best,
Peter

**Comment by Multifalcon** [comment]
Geat Job Plutonium. I work on this issue for a while and I am so happy you have found the way to fix
